"""Initial Enterprise Architecture

Revision ID: 2165005ffeea
Revises: 
Create Date: 2026-04-09 23:23:35.451288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2165005ffeea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armaduras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('estado_energia', sa.Enum('CRITICA', 'OPERATIVA', 'SOBRECARGA', name='nivelenergiaarmadura'), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_armaduras_id'), 'armaduras', ['id'], unique=False)
    op.create_index(op.f('ix_armaduras_is_deleted'), 'armaduras', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_armaduras_modelo'), 'armaduras', ['modelo'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_is_deleted'), 'usuarios', ['is_deleted'], unique=False)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('armadura_modelo', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'FINALIZADA', 'CANCELADA', name='estadoreserva'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fecha_fin > fecha_inicio', name='check_logica_temporal'),
    sa.ForeignKeyConstraint(['armadura_modelo'], ['armaduras.modelo'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_armadura_rango', 'reservas', ['armadura_modelo', 'fecha_inicio', 'fecha_fin'], unique=False)
    op.create_index('idx_usuario_estado', 'reservas', ['usuario_id', 'estado'], unique=False)
    op.create_index(op.f('ix_reservas_armadura_modelo'), 'reservas', ['armadura_modelo'], unique=False)
    op.create_index(op.f('ix_reservas_estado'), 'reservas', ['estado'], unique=False)
    op.create_index(op.f('ix_reservas_fecha_fin'), 'reservas', ['fecha_fin'], unique=False)
    op.create_index(op.f('ix_reservas_fecha_inicio'), 'reservas', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_reservas_id'), 'reservas', ['id'], unique=False)
    op.create_index(op.f('ix_reservas_usuario_id'), 'reservas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservas_usuario_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_fecha_inicio'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_fecha_fin'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_estado'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_armadura_modelo'), table_name='reservas')
    op.drop_index('idx_usuario_estado', table_name='reservas')
    op.drop_index('idx_armadura_rango', table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_usuarios_is_deleted'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_armaduras_modelo'), table_name='armaduras')
    op.drop_index(op.f('ix_armaduras_is_deleted'), table_name='armaduras')
    op.drop_index(op.f('ix_armaduras_id'), table_name='armaduras')
    op.drop_table('armaduras')
    # ### end Alembic commands ###
