"""Migracion inicial - Tabla Armaduras

Revision ID: 501616ef111d
Revises: 
Create Date: 2026-04-06 03:36:38.633822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501616ef111d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armaduras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('nivel_energia', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_armaduras_id'), 'armaduras', ['id'], unique=False)
    op.create_index(op.f('ix_armaduras_modelo'), 'armaduras', ['modelo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_armaduras_modelo'), table_name='armaduras')
    op.drop_index(op.f('ix_armaduras_id'), table_name='armaduras')
    op.drop_table('armaduras')
    # ### end Alembic commands ###
