"""agregar_tabla_reservas

Revision ID: 833729c6677b
Revises: 77eb7db57e80
Create Date: 2026-04-07 01:27:39.020016

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "833729c6677b"
down_revision: Union[str, Sequence[str], None] = "77eb7db57e80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("armadura_modelo", sa.String(), nullable=False),
        sa.Column("fecha_inicio", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fecha_fin", sa.DateTime(timezone=True), nullable=False),
        sa.Column("estado", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["armadura_modelo"],
            ["armaduras.modelo"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reservas_id"), "reservas", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reservas_id"), table_name="reservas")
    op.drop_table("reservas")
    # ### end Alembic commands ###
