"""Refactorización Enterprise: Mixins, Enums e Índices Compuestos

Revision ID: aeb4a9c598d2
Revises: f192049b5985
Create Date: 2026-04-09 23:05:21.454684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb4a9c598d2'
down_revision: Union[str, Sequence[str], None] = 'f192049b5985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('armaduras', sa.Column('estado_energia', sa.Enum('CRITICA', 'OPERATIVA', 'SOBRECARGA', name='nivelenergiaarmadura'), nullable=False))
    op.add_column('armaduras', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('armaduras', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('armaduras', 'modelo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_armaduras_is_deleted'), 'armaduras', ['is_deleted'], unique=False)
    op.drop_column('armaduras', 'nivel_energia')
    op.add_column('reservas', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('reservas', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('reservas', 'estado',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ACTIVA', 'FINALIZADA', 'CANCELADA', name='estadoreserva'),
               nullable=False)
    op.create_index('idx_armadura_rango', 'reservas', ['armadura_modelo', 'fecha_inicio', 'fecha_fin'], unique=False)
    op.create_index('idx_usuario_estado', 'reservas', ['usuario_id', 'estado'], unique=False)
    op.create_index(op.f('ix_reservas_armadura_modelo'), 'reservas', ['armadura_modelo'], unique=False)
    op.create_index(op.f('ix_reservas_estado'), 'reservas', ['estado'], unique=False)
    op.create_index(op.f('ix_reservas_fecha_fin'), 'reservas', ['fecha_fin'], unique=False)
    op.create_index(op.f('ix_reservas_fecha_inicio'), 'reservas', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_reservas_usuario_id'), 'reservas', ['usuario_id'], unique=False)
    op.drop_constraint(op.f('reservas_usuario_id_fkey'), 'reservas', type_='foreignkey')
    op.drop_constraint(op.f('reservas_armadura_modelo_fkey'), 'reservas', type_='foreignkey')
    op.create_foreign_key(None, 'reservas', 'armaduras', ['armadura_modelo'], ['modelo'], onupdate='CASCADE')
    op.create_foreign_key(None, 'reservas', 'usuarios', ['usuario_id'], ['id'], ondelete='RESTRICT')
    op.add_column('usuarios', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('usuarios', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('usuarios', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_usuarios_is_deleted'), 'usuarios', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_is_deleted'), table_name='usuarios')
    op.drop_column('usuarios', 'is_deleted')
    op.drop_column('usuarios', 'updated_at')
    op.drop_column('usuarios', 'created_at')
    op.drop_constraint(None, 'reservas', type_='foreignkey')
    op.drop_constraint(None, 'reservas', type_='foreignkey')
    op.create_foreign_key(op.f('reservas_armadura_modelo_fkey'), 'reservas', 'armaduras', ['armadura_modelo'], ['modelo'])
    op.create_foreign_key(op.f('reservas_usuario_id_fkey'), 'reservas', 'usuarios', ['usuario_id'], ['id'])
    op.drop_index(op.f('ix_reservas_usuario_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_fecha_inicio'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_fecha_fin'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_estado'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_armadura_modelo'), table_name='reservas')
    op.drop_index('idx_usuario_estado', table_name='reservas')
    op.drop_index('idx_armadura_rango', table_name='reservas')
    op.alter_column('reservas', 'estado',
               existing_type=sa.Enum('ACTIVA', 'FINALIZADA', 'CANCELADA', name='estadoreserva'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('reservas', 'updated_at')
    op.drop_column('reservas', 'created_at')
    op.add_column('armaduras', sa.Column('nivel_energia', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_armaduras_is_deleted'), table_name='armaduras')
    op.alter_column('armaduras', 'modelo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('armaduras', 'updated_at')
    op.drop_column('armaduras', 'created_at')
    op.drop_column('armaduras', 'estado_energia')
    # ### end Alembic commands ###
