"""add is_deleted to armaduras

Revision ID: f192049b5985
Revises: 1c1f4a623b5a
Create Date: 2026-04-07 03:09:42.777037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f192049b5985'
down_revision: Union[str, Sequence[str], None] = '1c1f4a623b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('armaduras', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('armaduras', 'is_deleted')
    # ### end Alembic commands ###
